Update init file based on logstash 2.1.1

diff --git a/condor/automation/logstash-condor-history b/condor/automation/logstash-condor-history
--- a/condor/automation/logstash-condor-history
+++ b/condor/automation/logstash-condor-history
@@ -6,12 +6,12 @@
 #   * Sections: 20.2, 20.3
 #
 ### BEGIN INIT INFO
-# Provides:          logstash
+# Provides:          logstash-condor-history
 # Required-Start:    $remote_fs $syslog
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: 
+# Short-Description:
 # Description:        Starts Logstash as a daemon.
 ### END INIT INFO
 
@@ -30,35 +30,45 @@ LS_USER=logstash
 LS_GROUP=logstash
 LS_HOME=/var/lib/logstash
 LS_HEAP_SIZE="500m"
-LS_JAVA_OPTS="-Djava.io.tmpdir=${LS_HOME}"
 LS_LOG_DIR=/var/log/logstash
 LS_LOG_FILE="${LS_LOG_DIR}/$name.log"
-LS_CONF_DIR=/etc/logstash/conf.d
+LS_CONF_DIR=/etc/logstash/condor_history.conf
 LS_OPEN_FILES=16384
 LS_NICE=19
 LS_OPTS=""
+
 
 [ -r /etc/default/$name ] && . /etc/default/$name
 [ -r /etc/sysconfig/$name ] && . /etc/sysconfig/$name
 
 program=/opt/logstash/bin/logstash
-args="agent -f  /etc/logstash/condor_history.conf -l ${LS_LOG_FILE} ${LS_OPTS}"
+args="agent -f ${LS_CONF_DIR} -l ${LS_LOG_FILE} ${LS_OPTS}"
+
+quiet() {
+  "$@" > /dev/null 2>&1
+  return $?
+}
 
 start() {
 
-
-  JAVA_OPTS=${LS_JAVA_OPTS}
+  LS_JAVA_OPTS="${LS_JAVA_OPTS} -Djava.io.tmpdir=${LS_HOME}"
   HOME=${LS_HOME}
-  export PATH HOME JAVA_OPTS LS_HEAP_SIZE LS_JAVA_OPTS LS_USE_GC_LOGGING
+  export PATH HOME LS_HEAP_SIZE LS_JAVA_OPTS LS_USE_GC_LOGGING
+
+  # chown doesn't grab the suplimental groups when setting the user:group - so we have to do it for it.
+  # Boy, I hope we're root here.
+  SGROUPS=$(id -Gn "$LS_USER" | tr " " "," | sed 's/,$//'; echo '')
+
+  if [ ! -z $SGROUPS ]
+  then
+	EXTRA_GROUPS="--groups $SGROUPS"
+  fi
 
   # set ulimit as (root, presumably) first, before we drop privileges
   ulimit -n ${LS_OPEN_FILES}
-  if [ ! -e /var/lib/logstash-condor-history ];
-  then
-      mkdir /var/lib/logstash-condor-history
-  fi
+
   # Run the program!
-  nice -n ${LS_NICE} chroot --userspec $LS_USER:$LS_GROUP / sh -c "
+  nice -n ${LS_NICE} chroot --userspec $LS_USER:$LS_GROUP $EXTRA_GROUPS / sh -c "
     cd $LS_HOME
     ulimit -n ${LS_OPEN_FILES}
     exec \"$program\" $args
@@ -86,7 +96,13 @@ stop() {
       sleep 1
     done
     if status ; then
-      echo "$name stop failed; still running."
+      if [ "$KILL_ON_STOP_TIMEOUT" -eq 1 ] ; then
+        echo "Timeout reached. Killing $name (pid $pid) with SIGKILL. This may result in data loss."
+        kill -KILL $pid
+        echo "$name killed with SIGKILL."
+      else
+        echo "$name stop failed; still running."
+      fi
     else
       echo "$name stopped."
     fi
@@ -118,6 +134,23 @@ force_stop() {
   fi
 }
 
+configtest() {
+  # Check if a config file exists
+  if [ ! "$(ls -A ${LS_CONF_DIR}/* 2> /dev/null)" ]; then
+    log_failure_msg "There aren't any configuration files in ${LS_CONF_DIR}"
+    exit 1
+  fi
+
+  JAVA_OPTS=${LS_JAVA_OPTS}
+  HOME=${LS_HOME}
+  export PATH HOME JAVA_OPTS LS_HEAP_SIZE LS_JAVA_OPTS LS_USE_GC_LOGGING
+
+  test_args="-f ${LS_CONF_DIR} --configtest ${LS_OPTS}"
+  $program ${test_args}
+  [ $? -eq 0 ] && return 0
+  # Program not configured
+  return 6
+}
 
 case "$1" in
   start)
@@ -133,7 +166,7 @@ case "$1" in
     ;;
   stop) stop ;;
   force-stop) force_stop ;;
-  status) 
+  status)
     status
     code=$?
     if [ $code -eq 0 ] ; then
@@ -143,14 +176,27 @@ case "$1" in
     fi
     exit $code
     ;;
-  restart) 
-    
-    stop && start 
+  restart)
+
+    quiet configtest
+    RET=$?
+    if [ ${RET} -ne 0 ]; then
+      echo "Configuration error. Not restarting. Re-run with configtest parameter for details"
+      exit ${RET}
+    fi
+    stop && start
+    ;;
+  configtest)
+    configtest
+    exit $?
     ;;
   *)
-    echo "Usage: $SCRIPTNAME {start|stop|force-stop|status|restart}" >&2
+    echo "Usage: $SCRIPTNAME {start|stop|force-stop|status|restart|configtest}" >&2
     exit 3
   ;;
 esac
 
 exit $?
+
+
+
